### ISSUE TITLE
Feature : add a scraper 

### ISSUE THREAD

**Issue by Blackhatfrance** [titanhw/go-proxy-checker#3]
Feature : add a scraper  of public proxy list

**Comment by titanhw** [comment]
We consider that the proxy server list should be managed by you. The purpose of this project is to provide proxy server availability verification. There may be another new project to obtain the proxy server according to the rules provided by the user.

**Comment by titanhw** [comment]
We consider that the proxy server list should be managed by you. The purpose of this project is to provide proxy server availability verification. There may be another new project to grab the proxy server list according to the rules provided by the user.
