### ISSUE TITLE
Panic Error on windows

### ISSUE THREAD

**Issue by bawzz234** [titanhw/go-proxy-checker#4]
Hi,

Thanks for creating such a useful tool. However, I couldn't check the proxies because an error kept showing up. 

`panic: interface conversion: interface {} is nil, not string`

Could you please fix this?

Best Regards

**Comment by xxtitan** [comment]
Can you provide more information? exp: the proxy file used for checking.

**Comment by bawzz234** [comment]
Sure, the proxy file was in .txt, and the proxies were in IP:Port format. It is in the attached file. 

Best Regards

[test.txt](https://github.com/titanhw/go-proxy-checker/files/10072516/test.txt)

**Comment by xxtitan** [comment]
Some lines do not conform to the format, like 77.65.50.118:51569:4433:20D1093EC98D5C406147
Please check this.
I will make it compatible with the wrong proxy format line in future versions.
